### ISSUE TITLE
Cannot bind to 8443: Address in use

### ISSUE THREAD

**Issue by lknite** [hectorm/docker-udptunnel#3]
```
$ k logs -f udptunnel-bb5c459f8-6pxwz
Listening for TCP connections on 0.0.0.0:8443
Cannot bind to 8443: Address in use
```

I think I might be running into this [issue](https://github.com/gentry0520/udptunnel/issues/8), could this fix possibly be needed in the source code you are using as well?

**Comment by hectorm** [comment]
The issue you indicate is from a different code base, although the project is called the same. This Docker image uses [hectorm/udptunnel](https://github.com/hectorm/udptunnel).

Could you please indicate how to reproduce the error? I have not been able to reproduce it.

![](https://user-images.githubusercontent.com/852266/196005508-04a3e2b2-e587-40f1-b2b4-2b7b0606bd66.png)

**Comment by lknite** [comment]
I'm not sure how, but it might be kubernetes related ... to reproduce would require having a kubernetes cluster to run in.  I'm going to go ahead and close out the case.  Looks like 'udp2raw' would work for me, except that I need to use localhost which winpcap doesn't support, which brings me back to udptunnel.  Not sure what to do now.  Will keep looking into it.

**Comment by splatch** [comment]
For the record .. I had earlier version of the image (one published at least 3 years ago), running in docker compose for quite long time. It started to crash recently with 'Cannot bind to 1446: Address in use'. After a bit of tinkering I found out that after adjusting `-s 1446` to `-s 0.0.0.0:1446` whole thing started to work. Not sure why, but it have helped.
